src/Entity/Figure.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;
use Cocur\Slugify\Slugify;

/**
 * @ORM\Entity(repositoryClass="App\Repository\FigureRepository")
 * @UniqueEntity("nom")
 */
class Figure
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $nom;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="datetime")
     */
    private $ajout_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $modif_at;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Media", mappedBy="figures", cascade={"persist"})
     */
    private $media;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $imageUne;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Groupe", inversedBy="figures")
     */
    private $groupe;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="figures_user")
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="figure", orphanRemoval=true)
     */
    private $comments;

    public $video;

  
    public function __construct()
    {
        $this->media = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getSlug(): string
    {
        return (new Slugify())->slugify($this->nom);
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getAjoutAt(): ?\DateTimeInterface
    {
        return $this->ajout_at;
    }

    public function setAjoutAt(\DateTimeInterface $ajout_at): self
    {
        $this->ajout_at = $ajout_at;

        return $this;
    }

    public function getModifAt(): ?\DateTimeInterface
    {
        return $this->modif_at;
    }

    public function setModifAt(\DateTimeInterface $modif_at): self
    {
        $this->modif_at = $modif_at;

        return $this;
    }

    /**
     * @return Collection|Media[]
     */
    public function getMedia(): Collection
    {
        return $this->media;
    }

    public function addMedium(Media $medium): self
    {
        if (!$this->media->contains($medium)) {
            $this->media[] = $medium;
            $medium->setFigures($this);
        }

        return $this;
    }

    public function removeMedium(Media $medium): self
    {
        if ($this->media->contains($medium)) {
            $this->media->removeElement($medium);
            // set the owning side to null (unless already changed)
            if ($medium->getFigures() === $this) {
                $medium->setFigures(null);
            }
        }

        return $this;
    }

    public function getImageUne()
    {
        return $this->imageUne;
    }

    public function setImageUne($imageUne)
    {
        $this->imageUne = $imageUne;

        return $this;
    }

    public function getGroupe(): ?Groupe
    {
        return $this->groupe;
    }

    public function setGroupe(?Groupe $groupe): self
    {
        $this->groupe = $groupe;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setFigure($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getFigure() === $this) {
                $comment->setFigure(null);
            }
        }

        return $this;
    }
}

src/Form/FigureType.php
<?php

namespace App\Form;

use App\Entity\Media;
use App\Entity\Figure;
use App\Entity\Groupe;
use App\Form\MediaType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Validator\Constraints\Image;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;

class FigureType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        /** @var Figure|null $figure */
        $figure = $options['data'] ?? null;
        $isEdit = $figure && $figure->getId();
        

        $imageConstraints = [
            new Image([
                'maxSize' => '5M'
            ])
        ];

        if (!$isEdit) {
            $imageConstraints[] = new NotNull([
                'message' => 'Svp uploader une image',
            ]);
        }

        $builder
            ->add('nom')
            ->add('description')
            ->add('image_une', Filetype::class, [
                'label' => 'Image à la une',
                'required' => false,
                'mapped' => false,
                'constraints' => $imageConstraints,
                ])
            ->add('groupe', EntityType::class, [
                'class' => Groupe::class,
                'choice_label' => 'nom'
                ])
            ->add('media', CollectionType::class, [
                'entry_type' => MediaType::class,
                'entry_options' => ['label' => false],
                'allow_add' => true,
                'by_reference' => false,
                'allow_delete' => true,
                'label' => false,
            ])
            ->add('video', CollectionType::class, [
                'entry_type' => MediaType::class,
                'entry_options' => ['label' => false],
                'allow_add' => true,
                'by_reference' => false,
                'allow_delete' => true,
                'label' => false,
            ])
            ->add('save', SubmitType::class, [
                'label' => 'Enregistrer'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Figure::class,
        ]);
    }
}

src/Controller/FigureController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Entity\Media;
use App\Entity\Figure;
use App\Entity\Groupe;
use App\Entity\Comment;
use App\Form\FigureType;
use App\Form\CommentType;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;

class FigureController extends AbstractController
{
  
    /**
     * @Route("/figure/{slug}-{id}", name="figure_show", requirements={"slug": "[a-z0-9\-]*"})
     */
    public function show(Figure $figure, string $slug, Request $request, ObjectManager $manager, UserInterface $user = null)
    {
        if ($figure->getSlug() !== $slug) {
            return $this->redirectToRoute(
                'figure_show', [
                'id' => $figure->getId(),
                'slug' => $figure->getSlug()
                ], 301
            );
        }
        $comment = new Comment();
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $comment->setCreatedAt(new \DateTime())
                ->setFigure($figure)
                ->setUser($user);
            $manager->persist($comment);
            $manager->flush();

            return $this->redirectToRoute(
                'figure_show', [
                'id' => $figure->getId(),
                'slug' => $figure->getSlug()
                ], 301
            );
        }
        
        return $this->render(
            'figure/show.html.twig', [
            'figure' => $figure,
            'commentForm' => $form->createView()
            ]
        );
    }
}

templates/figure/show.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
   <link href="{{ asset('css/show.css') }}" rel="stylesheet" />
{% endblock %}

{% block body %}
<div class="container mt-4">
    {% for message in app.flashes('success') %}
    <div class="alert alert-success">
        {{ message }}
    </div>
    {% endfor %}  
    <div>
        {% if 'placeholder' in figure.ImageUne %}
            <img classe="image_une" src="{{ figure.ImageUne }}" style="max-width: 100%;">   
        {% else %}    
            <img classe="image_une" src="{{ asset('uploads/' ~ figure.ImageUne) }}" style="max-width: 100%;">
        {% endif %}      
    </div>
    <br>
    {%for image in figure.media %}
        <div class="responsive">
            <div class="gallery">
                {% if '.jpeg' in image.url %}
                    <a href="{{ asset('uploads/' ~ image.url) }}" target="_blank"><img src="{{ asset('uploads/' ~ image.url) }}" class="galerie"></a>
                {% elseif 'placeholder' in image.url %}
                    <a href="{{ image.url }}" target="_blank"><img src="{{ image.url }}" class="galerie"></a>
                {% else %}
                    <div class="iframe-resp">{{ image.url | raw }}</div>
                {% endif %}
            </div>
        </div>
    {% endfor %}
    <div class="clearfix"></div>
    <div class="post-details">
        <h1>{{ figure.nom}}</h1>
        <div class="post-footer d-flex align-items-center flex-column flex-sm-row">
            <div class="title"><span>{{ figure.user.username }}</span></div>
            <div class="d-flex align-items-center flex-wrap">
            {% if figure.modifAt %}           
                <div class="date"><i class="icon-clock"></i>mis à jour le {{ figure.modifAt | date('d/m/Y') }}</div>
            {% else %}
                <div class="date"><i class="icon-clock"></i>ajouté le {{ figure.ajoutAt | date('d/m/Y') }}</div>
            {% endif %}
            <div class="comments meta-last"><i class="icon-comment"></i>{{ figure.comments | length }}</div>
        </div>
    </div>       
    <div style="margin-top: 30px">
        {{ figure.description | raw | nl2br }}
    </div>
    <hr>
    <div class="post-tags"><a href="{{ path('groupe_index', {'id': figure.groupe.id }) }}" class="tag">{{ figure.groupe.nom }}</a></div>
        <div class="post-comments">
            <header>
                <h3 class="h6">Commentaires <span class="no-of-comments">({{ figure.comments | length }})</span></h3>
            </header>
            {% for comment in figure.comments %}
            <div class="comment">
                <div class="comment-header d-flex justify-content-between">
                    <div class="user d-flex align-items-center">
                    <div class="image"><img src="{{ asset('img/user.svg') }}" alt="..." class="img-fluid rounded-circle"></div>
                    <div class="title"><strong>{{ comment.user.username }}</strong><span class="date">Publié le {{ comment.createdAt | date('d/m/Y') }}</span></div>
                </div>
            </div>
            <div class="comment-body">
                <p>{{ comment.content | raw }}</p>
            </div>
        </div>
        {% endfor %}

        {% if app.user %}
            {{ form_start(commentForm) }}
            {{ form_row(commentForm.content) }}
                <button type="submit" class="btn btn-secondary">Commenter !</button>
            {{ form_end(commentForm) }}
        {% else %}
            <a href="{{ path('user_login') }}"><h3>Connectez-vous pour laisser un message !</h3></a>
        {% endif %}
    </div>
</div>    
{% endblock %}